// GENERATED by scripts/gen-authz.mjs from the project's OpenAPI contracts
// (specs/design/components/*/openapi.yaml and
// specs/design/components/*/dependencies/*.openapi.yaml).
// Do not edit by hand, and do not retype any of these values anywhere else.
// Re-run `npm run gen` after a contract changes. COMMIT this file: the
// per-component image build cannot see the specs tree.
//
// This table is what a screen is gated on. src/authz/screens.ts names the
// operation each screen LOADS; holding that operation's scope is what makes the
// screen reachable. Nothing else in the app decides that.

import type { Scope } from "./roles.gen";

/** What the gateway demands of a caller before it will pass an operation on. */
export type OperationRequirement =
  | { readonly kind: "public" }
  | { readonly kind: "signedIn" }
  | { readonly kind: "scope"; readonly scope: Scope };

/** "<METHOD> <path template>" as the contract spells it, e.g. "GET /me/claims". Sorted. */
export type OperationKey =
  | "GET /claims"
  | "GET /employees"
  | "GET /export-batches"
  | "GET /me"
  | "GET /me/claims"
  | "GET /me/claims/{claimId}"
  | "GET /me/team/claims"
  | "PATCH /employees/{employeeId}/manager"
  | "POST /claims/export"
  | "POST /claims/{claimId}/approve"
  | "POST /claims/{claimId}/reject"
  | "POST /me/claims"
  | "POST /me/team/claims/{claimId}/approve"
  | "POST /me/team/claims/{claimId}/reject"
  | "PUT /me/claims/{claimId}";

export const OPERATIONS: Record<OperationKey, OperationRequirement> = {
  "GET /claims": { kind: "scope", scope: "claims:read-all" },
  "GET /employees": { kind: "scope", scope: "employees:read" },
  "GET /export-batches": { kind: "scope", scope: "claims:export" },
  "GET /me": { kind: "signedIn" },
  "GET /me/claims": { kind: "scope", scope: "claims:read" },
  "GET /me/claims/{claimId}": { kind: "scope", scope: "claims:read" },
  "GET /me/team/claims": { kind: "scope", scope: "claims:read-team" },
  "PATCH /employees/{employeeId}/manager": { kind: "scope", scope: "employees:manage" },
  "POST /claims/export": { kind: "scope", scope: "claims:export" },
  "POST /claims/{claimId}/approve": { kind: "scope", scope: "claims:decide-finance" },
  "POST /claims/{claimId}/reject": { kind: "scope", scope: "claims:decide-finance" },
  "POST /me/claims": { kind: "scope", scope: "claims:submit" },
  "POST /me/team/claims/{claimId}/approve": { kind: "scope", scope: "claims:decide-manager" },
  "POST /me/team/claims/{claimId}/reject": { kind: "scope", scope: "claims:decide-manager" },
  "PUT /me/claims/{claimId}": { kind: "scope", scope: "claims:submit" },
};

export function isOperationKey(value: string): value is OperationKey {
  return Object.prototype.hasOwnProperty.call(OPERATIONS, value);
}
