// GENERATED by scripts/gen-authz.mjs from specs/design/security.json.
// Do not edit by hand, and do not retype any of these values anywhere else.
// Re-run `npm run gen` after the design changes. COMMIT this file: the
// per-component image build cannot see the specs tree.

export type Scope =
  | "claims:decide-finance"
  | "claims:decide-manager"
  | "claims:export"
  | "claims:read"
  | "claims:read-all"
  | "claims:read-team"
  | "claims:submit"
  | "employees:manage"
  | "employees:read";

export type Role =
  | "Employee"
  | "FinanceReviewer"
  | "LineManager";

/** Every handle the catalog declares, sorted. */
export const SCOPES: readonly Scope[] = ["claims:decide-finance", "claims:decide-manager", "claims:export", "claims:read", "claims:read-all", "claims:read-team", "claims:submit", "employees:manage", "employees:read"];

/** Every role a person can hold, sorted. Service-kind roles are not here. */
export const ROLES: readonly Role[] = ["Employee", "FinanceReviewer", "LineManager"];

/** What each role grants. heldRoles() projects the caller's scopes through this. */
export const ROLE_GRANTS: Record<Role, readonly Scope[]> = {
  "Employee": ["claims:read", "claims:submit", "employees:read"],
  "FinanceReviewer": ["claims:decide-finance", "claims:export", "claims:read-all", "employees:manage", "employees:read"],
  "LineManager": ["claims:decide-manager", "claims:read", "claims:read-team", "claims:submit", "employees:read"],
};

/** The directory groups a role is assigned to — what NoAccess tells a user to ask for. */
export const ROLE_ASSIGN_TO: Record<Role, readonly string[]> = {
  "Employee": ["Employees"],
  "FinanceReviewer": ["Finance"],
  "LineManager": ["Managers"],
};

/** The roles that can hand this one out — who NoAccess tells a user to ask. */
export const ROLE_ASSIGNABLE_BY: Record<Role, readonly string[]> = {
  "Employee": [],
  "FinanceReviewer": [],
  "LineManager": [],
};

export function isScope(value: string): value is Scope {
  return (SCOPES as readonly string[]).includes(value);
}
