// GENERATED by scripts/gen-authz.mjs from specs/design/security.json roles[], in
// DECLARED order — the first is the default persona `?role=` falls back to.
// Do not edit by hand. Re-run `npm run gen` after the design changes.
//
// THE MOCK NEVER WIDENS: each role's grants are exactly what security.json
// declares. A role that cannot reach its own screen is a DESIGN DEFECT to
// report, never a mock to loosen.

export const mockRoles: readonly { readonly name: string; readonly grants: readonly string[] }[] = [
  { name: "Employee", grants: ["claims:read", "claims:submit", "employees:read"] },
  { name: "LineManager", grants: ["claims:decide-manager", "claims:read", "claims:read-team", "claims:submit", "employees:read"] },
  { name: "FinanceReviewer", grants: ["claims:decide-finance", "claims:export", "claims:read-all", "employees:manage", "employees:read"] },
];
